### ISSUE TITLE
Add Gitter and Badges

### ISSUE THREAD

**Issue by Hammster** [toinfiniityandbeyond/Tilemap#8]
Hi there,

Gitter would be a good starting point for contributors to get some feedback outside of issues and pull requests. 

https://gitter.im

Also everyone loves extra badges.

![Tested on Unity 5.4.0f3](https://img.shields.io/badge/Tested%20on%20unity-5.4.0f3-blue.svg?style=flat-square)
https://img.shields.io/badge/Tested%20on%20unity-5.4.0f3-blue.svg?style=flat-square
![Tested on Unity 5.4.0f3](https://img.shields.io/badge/Gitter-Join%20%E2%9E%A4-green.svg?style=flat-square)
https://img.shields.io/badge/Gitter-Join%20%E2%9E%A4-green.svg?style=flat-square

**Comment by paullj** [comment]
Done :) although I don't know if I've done it right, I've never used glitter before

EDIT: here is the link for the glitter [![Gitter](https://badges.gitter.im/unity-tilemap/Lobby.svg)](https://gitter.im/unity-tilemap/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
